### ISSUE TITLE
Login issue within new visual studio project

### ISSUE THREAD

**Issue by justinbakker** [maikebing/GitLab.VisualStudio#43] opened 2019-01-31 09:00 UTC
### Installed product versions
- Visual Studio: 2017 community edition
- This extension: 1.0.167

### Description
I'm getting a login error when connection from a new project. Exisiting projects still work and authenticate normally however creating a new project gives an error on login.

![image](https://user-images.githubusercontent.com/47208455/52042910-a9e3f600-253e-11e9-8cec-00dd420ca4d4.png)

### Steps to recreate
1. Start visual studio
2. In the team explorer trying to connect to my gitlab server
3. Or creating a new project an trying to connect to the gitlab server.

### Current behavior
Throwing an error on login while login on exisiting projects still work.
![image](https://user-images.githubusercontent.com/47208455/52043029-f0d1eb80-253e-11e9-99ba-0fca4eee99ec.png)

**Comment by roperjonathan** [comment] 2019-02-01 16:50
I'm getting the same issue.

**Comment by infprg01n** [comment] 2019-02-02 21:19
Same...

**Comment by JerrodV** [comment] 2019-02-04 17:03
I have the same problem. I get the same screen if I try to log from Team Explorer/Sync or Manage Connections with GitLab APIv3 Oauth2, or GitLab APIv4 Oauth2. If I try to log in with Auto Discovery, it says:
![image](https://user-images.githubusercontent.com/8077761/52223796-0b240600-286c-11e9-8766-75d043cf0c17.png)

If I open a project that already tracks a remote branch everything works like it should. 

I have tried clearing all references to GitLab from Credential Manager and the problem persists.

**Comment by AndrewSorokin** [comment] 2019-02-08 12:05
Same, v1.0.176

Besides, sniffing authentication response with HTTP 200 OK gives me that JSON:

{"id":4,"name":"Сорокин Андрей Владимирович","username":"avsorokin","state":"active","avatar_url":"http://mygitlabserver.mycompany.ru/uploads/-/system/user/avatar/4/avatar.png","web_url":"http://mygitlabserver.mycompany.ru/avsorokin","created_at":"2018-12-25T10:09:14.273Z","bio":"","location":"","public_email":"","skype":"","linkedin":"","twitter":"","website_url":"","organization":"","last_sign_in_at":"2019-02-08T08:58:50.336Z","confirmed_at":"2018-12-25T10:09:14.136Z","last_activity_on":"2019-02-08","email":"myemail@mycompany.ru","theme_id":1,"color_scheme_id":1,"projects_limit":100000,"current_sign_in_at":"2019-02-08T11:36:12.421Z","identities":[{"provider":"ldapmain","extern_uid":"cn=сорокин андрей владимирович,ou=mycompany users,dc=mycompany,dc=ru"}],"can_create_group":true,"can_create_project":true,"two_factor_enabled":true,"external":false,"private_profile":false}

**Comment by TinyCrocodile** [comment] 2019-02-08 19:10
I have the same problem using VS2017Comunity and v1.0.176 as well. Never used it bevore have no existing connections. Not able to make it work. 
I created gitlab account by signing in with github account. Just in case it matters...

**Comment by maikebing** [comment] 2019-02-10 06:39
Typically, it may be that the user name password is incorrect

**Comment by infprg01n** [comment] 2019-02-10 09:33
It's not incorrect login issue. Because with same credentials you can clone and then commit/push/fetch/... but you just can login over connect window to browse etc...

**Comment by TinyCrocodile** [comment] 2019-02-10 10:05
No i just tryed and copy paste password and username from a textfile. Login in VS-Extension faild and login onto gitlab website worked.

**Comment by Hubert9559** [comment] 2019-02-10 23:44
Same problem, login on website works, in VS "Failed to login. Requested value 'AutoDiscovery' was not found."

**Comment by gyzod** [comment] 2019-02-11 21:01
Same thing here with VS2017

**Comment by maikebing** [comment] 2019-02-19 04:34
New version 1.0.177, who tested it, what's the problem?

**Comment by cjmny** [comment] 2019-02-22 15:13
Version 1.0.178 still has the login issue for me.

**Comment by Tuumke** [comment] 2019-02-27 07:43
Having issues as well. Using LDAP username + pass, LDAP username + access token, APIv4 and 2FA.
![afbeelding](https://user-images.githubusercontent.com/935617/53473826-be4ade00-3a6b-11e9-8e95-b7acba64662d.png)

**Comment by maikebing** [comment] 2019-02-27 07:58
@Tuumke   @cjmny    @GoodLeak  Can you give me a test account?

**Comment by gsanya** [comment] 2019-02-27 08:41
I have an account on my laptop, it is logged in, and the existing project works (vs2015 community). But now I tried to login to another computer(vs2017 community) with the same credentials (the credentials work on the gitlab website) and I get the same above mentioned errors.

**Comment by fabm3n** [comment] 2019-02-27 08:41
I also having the same issue. Test account created.

**Comment by fabm3n** [comment] 2019-02-27 08:44
> I have an account on my laptop, it is logged in, and the existing project works (vs2015 community). But now I tried to login to another computer(vs2017 community) with the same credentials (the credentials work on the gitlab website) and I get the same above mentioned errors.

Same Problem. Pc with vs2017 community logged in 6 months ago and new vs2017 community installation on a laptop dosn't work.
For reproduction you can check if the problem occures in a vm.

**Comment by Tuumke** [comment] 2019-02-27 09:33
> @Tuumke @cjmny @GoodLeak Can you give me a test account?

Sorry, was responding in https://github.com/maikebing/GitLab.VisualStudio/issues/17.
It's a private server, so no i cannot give you test account. But, i also created an account on gitlab.com and having same issues and errors. 
Just created an account @ gitlab.com to try and see if it works there. 
Using server https://gitlab.com with username and password and autodiscovery:
![afbeelding](https://user-images.githubusercontent.com/935617/53477426-f60a5380-3a74-11e9-867a-3315fbf025fb.png)
Using server https://gitlab.com with e-mail adress, pass, auto discovery:
![afbeelding](https://user-images.githubusercontent.com/935617/53477462-0d494100-3a75-11e9-93f8-be3163398208.png)
Using server https://gitlab.com with username or e-mail, token, auto discovery, 2FA:
![afbeelding](https://user-images.githubusercontent.com/935617/53477545-3d90df80-3a75-11e9-8d0a-8d4a175e14a9.png)

**Comment by maikebing** [comment] 2019-02-27 11:25
@Tuumke   It looks like your user password is incorrect. More details can read  
 https://github.com/maikebing/GitLab.VisualStudio/blob/master/README.md

**Comment by maikebing** [comment] 2019-02-27 11:26
When you login with a user name and password.
For the new version of Gitlab：

https//gitlab.com or your GitLab server
input your email address or username
your password (not the token)
use "GitLab ApiV4 Oauth2" don't use "API v4" as the instructions direct
Two-Factor : Off
For older versions of Gitlab

Your GitLab server
input your email address or username
your password (not the token) 1.use "GitLab ApiV3 Oauth2" or "API v3"
by Brett Winters

When you login with 2FA :
In GitLab, [top right] go to Settings then Access Tokens (left menu)
Enter a name & expire time (optional).
Check off "api" as the scope.
Click "Create Personal Access Token". This will appear in a textbox at the TOP of the page.
In Visual Studio, click "Connect" beside GitLab.
Enter your GitLab Username and paste in the Access Token.
Change it to "API v4" instead of "API v4 OAUTH2".
Make sure "Two Factor Authentication" is CHECKED.
Save. You're DONE.
When you login with LDAP credentials :
If you create a personal access token (https://yourgitlaburl.com/profile/personal_access_tokens) and select 2fa and use your ldap username + your PAT you will be able to login and use the plug-in.

by dominicdejacomo

**Comment by gsanya** [comment] 2019-02-27 11:28
Yeah, I get the same error. It seems like that password is wrong. But when I try to log in to the gitlab webpage with the same credentials I can log in. So the user name and password are correct.

**Comment by Tuumke** [comment] 2019-02-27 11:55
> Yeah, I get the same error. It seems like that password is wrong. But when I try to log in to the gitlab webpage with the same credentials I can log in. So the user name and password are correct. And something with the vs authentication is wrong.

Same here. I can login with same credentials in GitLab (on premise and gitlab.com) but not with the GitLab for VS.

**Comment by FlyingGardenGnomeStudios** [comment] 2019-02-27 14:55
I'm getting the exact same issue as @Tuumke and I've tried the same things.
It may be completely unrelated, but I tried connecting GitLab through Sourcetree and received a similar issue with authentication. (It connects to my GitHub just ftine, but not GitLab)

**Comment by JerrodV** [comment] 2019-02-27 16:33
> I'm getting the exact same issue as @Tuumke and I've tried the same things.
> It may be completely unrelated, but I tried connecting GitLab through Sourcetree and received a similar issue with authentication. (It connects to my GitHub just ftine, but not GitLab)

Today I also went the SourceTree route but my account credentials worked fine. Also, I am able to work with an existing repo and it works fine, although, the UI is set up in such a way that I believe it 'thinks' it is not connected. Consider the following:

In this project I am able to make changes and sync with the remote server.
![image](https://user-images.githubusercontent.com/8077761/53505627-d590c800-3a79-11e9-88a2-9969af5289c9.png)

However, if I go to the sync tab and attempt the same thing, I see this:
![image](https://user-images.githubusercontent.com/8077761/53505468-7fbc2000-3a79-11e9-9d49-88c5173dc9c8.png)

Nothing in that looks like the extension is aware that I have a connection to GitLabs. It doesn't think I track a remote branch, but it is clearly in the settings and functional:
![image](https://user-images.githubusercontent.com/8077761/53505839-4e901f80-3a7a-11e9-87e9-5b55db0728d9.png)

The real issue comes in to play when I need to pull a repo for the first time. In order to do that I need to pass that login on the sync tab and it has been ridiculously unreliable since the first day I installed this extension (like a year ago or more). If I use SourceTree or Git GUI to pull the project I can then manipulate the remote repo using the extension just fine despite the it not being able to figure out what is going on with the login.

**Comment by FlyingGardenGnomeStudios** [comment] 2019-02-27 19:48
Very strange, I did nothing to change and tried to sign in again on VS after about 5 hrs and it worked first time. Tried on SourceTree and I'm still getting the error.

No idea why

**Comment by maikebing** [comment] 2019-02-28 10:53
I can't reproduce the problem, who can debug it?

**Comment by fabm3n** [comment] 2019-02-28 11:12
just install vs17 on a fresh machine then you can debug it.
I'll try to debug it later,

**Comment by Tuumke** [comment] 2019-02-28 12:10
Do you have a short instruction in how to debug this?

**Comment by maikebing** [comment] 2019-02-28 12:12
https://stackoverflow.com/questions/9281662/how-to-debug-visual-studio-extensions  
@Tuumke

**Comment by Tuumke** [comment] 2019-02-28 12:44
> https://stackoverflow.com/questions/9281662/how-to-debug-visual-studio-extensions
> @Tuumke

Sorry, that's out of my league i think. And don't have time atm to figure out how exaclty (when i lauchn my solution and select properties, i don't see these options)

**Comment by JerrodV** [comment] 2019-02-28 14:09
As a suggestion on how to reproduce, perhaps try using windows Credential Manager to remove the credentials added by the extension. My problems began after losing my primary hard drive, so on a fresh install of windows, fresh install of Visual Studio 2017 Community and the current version of the plugin. Cleaning my credentials does not help, so may be the step you are missing to seeing the fail login attempts.

**Comment by cjmny** [comment] 2019-02-28 18:07
> As a suggestion on how to reproduce, perhaps try using windows Credential Manager to remove the credentials added by the extension. My problems began after losing my primary hard drive, so on a fresh install of windows, fresh install of Visual Studio 2017 Community and the current version of the plugin. Cleaning my credentials does not help, so may be the step you are missing to seeing the fail login attempts.

This would be my suggestion as well.  I experienced the issue on a fresh install of VS 2017.

**Comment by banjosteve** [comment] 2019-02-28 19:08
We're experiencing the same issue on a fresh install of VS 2017 (15.9.7) and Gitlab extension 1.0.177

We run our own instance of Gitlab and can see successful authentications from the extension in the GitLab logs, but the extension responds with:

> Failed to login
Please checkyour username or password!
Last tryV4:Not login yet

**Comment by maikebing** [comment] 2019-02-28 23:29
@banjosteve  
When you login with 2FA :
In GitLab, [top right] go to Settings then Access Tokens (left menu)
Enter a name & expire time (optional).
Check off "api" as the scope.
Click "Create Personal Access Token". This will appear in a textbox at the TOP of the page.
In Visual Studio, click "Connect" beside GitLab.
Enter your GitLab Username and paste in the Access Token.
Change it to "API v4" instead of "API v4 OAUTH2".
Make sure "Two Factor Authentication" is CHECKED.
Save. You're DONE.
When you login with LDAP credentials :
If you create a personal access token (https://yourgitlaburl.com/profile/personal_access_tokens) and select 2fa and use your ldap username + your PAT you will be able to login and use the plug-in.

**Comment by banjosteve** [comment] 2019-03-01 01:19
> @banjosteve
> When you login with 2FA :
> In GitLab, [top right] go to Settings then Access Tokens (left menu)
> Enter a name & expire time (optional).
> Check off "api" as the scope.
> Click "Create Personal Access Token". This will appear in a textbox at the TOP of the page.
> In Visual Studio, click "Connect" beside GitLab.
> Enter your GitLab Username and paste in the Access Token.
> Change it to "API v4" instead of "API v4 OAUTH2".
> Make sure "Two Factor Authentication" is CHECKED.
> Save. You're DONE.
> When you login with LDAP credentials :
> If you create a personal access token (https://yourgitlaburl.com/profile/personal_access_tokens) and select 2fa and use your ldap username + your PAT you will be able to login and use the plug-in.

Thanks @maikebing, unfortunately, we have done all of that. Our GitLab instance even recognizes the successful authentication, but the extension seems to be blocking somewhere.

**Comment by Tuumke** [comment] 2019-03-01 07:52
@maikebing btw, we run on 1.0.177 but there are no release notes yet? 
https://github.com/maikebing/GitLab.VisualStudio/blob/master/CHANGELOG.md
What did you change between V1.0.160 and 1.0.177? And can we somehow download previous versions? For GitHub there is a revert button
![image](https://user-images.githubusercontent.com/935617/53624099-57f6c480-3bff-11e9-9d70-5a29bd4d87fd.png)
But for GitLab it's just uninstall / disable
![image](https://user-images.githubusercontent.com/935617/53624111-66dd7700-3bff-11e9-99ea-0fe86dd45ff7.png)

**Comment by maikebing** [comment] 2019-03-01 07:59
@Tuumke  
 
![2019-03-01 155720](https://user-images.githubusercontent.com/3445167/53624332-e0df2180-3c3a-11e9-8cd7-c289b2556f25.jpg)
Here may be the only difference

**Comment by Tuumke** [comment] 2019-03-01 08:03
Wait.. 1.0.178 is newer then 1.0.177 :-O 
Can you get me the older releases?

**Comment by maikebing** [comment] 2019-03-01 08:06
@Tuumke    
https://ci.appveyor.com/project/MaiKeBing/gitlab-visualstudio/history

open  a " history  build"  , find  Artifacts page , download it !

**Comment by Tuumke** [comment] 2019-03-01 08:29
This one works:
https://ci.appveyor.com/project/MaiKeBing/gitlab-visualstudio/builds/20928730/artifacts
1.0.166
Using LDAP + PAT + 2FA + APIv4
Now it updated again automaticly to 1.0.177 and login works :-S in the same way.. 
My mind is blown..

**Comment by TinyCrocodile** [comment] 2019-03-02 08:32
Ok thx i will try if this works for me as well

**Comment by Tuumke** [comment] 2019-03-02 12:15
> 
> 
> Ok thx i will try if this works for me as well

Dont forget:
Deinstall GitLab 1.0.177
Install 1.0.166 from appveyor link
Login to gitlab
Logout
Restart VS, check if it updated then login again

**Comment by alokhom** [comment] 2019-03-03 17:54
1.0.178 works fine with APIv4 + 2FA checked in for all gitlab installations.

**Comment by yog-muskrat** [comment] 2019-03-04 07:29
We have the same problem.  
@Tuumke's solution seems to work for us.

**Comment by kvtdeveloper** [comment] 2019-03-05 14:44
We have the same problem.
@Tuumke's solution seems to work for us too.

**Comment by gudaol** [comment] 2019-03-08 12:51
I have the same issue with 1.0.177

**Comment by maikebing** [comment] 2019-03-08 13:20
> 
> Otto Milvang
>  
> Login doesn't work.
> From wireshark I saw that I got an access token and also got a json
> {
> "id": 2,
> "name": "Otto Milvang",
> "username": "otto",
> "state": "active",
> "avatar_url": "https://www.gravatar.com/avatar/...",
> "web_url": "http://192.168.10.10/otto",
> "created_at": "2016-12-23T13:16:06.975Z",
> "bio": null,
> ....
> "projects_limit": 1000,
> "current_sign_in_at": "2019-03-06T09:01:39.016Z",
> "identities": [],
> "can_create_group": true,
> "can_create_project": true,
> "two_factor_enabled": false,
> "external": false,
> "private_profile": null,
> "is_admin": true
> }
> Still the response says "Not login yet"

**Comment by JerrodV** [comment] 2019-03-14 02:12
I was able to get this working as usual by reverting to the older version as well: 

> @Tuumke
> https://ci.appveyor.com/project/MaiKeBing/gitlab-visualstudio/history
> 
> open a " history build" , find Artifacts page , download it !

Sorry, not at the problem machine so can't check the version. Will edit.

**Comment by Hetflik** [comment] 2019-03-14 08:22
Unfortunately reverting is not working for me, because there is no "Publish to gitlab" with login button under sync in older versions for some reason...

**Comment by screig** [comment] 2019-03-14 09:51
Current version on Visual Studio Gallery did not work for me either, the AppVoyer version does.

**Comment by Ddog800** [comment] 2019-03-14 18:09
Also running into this problem. Migrated a project to Gitlab this morning and am now trying to get the Gitlab extension running in VS. At this point I've lost 3 hours just trying to get this thing going. 30 mins to find where to log in, and now that I've found that I'm unable to log in anyway. Hopefully these issues will be ironed out. For now, I may have have to revert to the raw git integration VS provides. Not ideal.....

**Comment by maikebing** [comment] 2019-03-17 08:52
Hi, everyone, please test the new version! If you have any questions, please reply to me.

https://ci.appveyor.com/project/MaiKeBing/gitlab-visualstudio/builds/23132899/artifacts

**Comment by gudaol** [comment] 2019-03-17 18:27
Seems to work! Or, at least, i logged in! Thanks!

**Comment by Hetflik** [comment] 2019-03-18 06:11
No problem with login in 1.0.180 with GitLab CE (I tried password and token). 
In Team Explorer Home I can see only one new button (Graphs) and it only shws "Object reference not set to an instance of an object." on top of the panel.

**Closed** 2019-03-25 04:00 UTC
Labels: bug, help wanted

**Comment by arcotek-ltd** [comment] 2019-04-07 00:44
> Also running into this problem. Migrated a project to Gitlab this morning and am now trying to get the Gitlab extension running in VS. At this point I've lost 3 hours just trying to get this thing going. 30 mins to find where to log in, and now that I've found that I'm unable to log in anyway. Hopefully these issues will be ironed out. For now, I may have have to revert to the raw git integration VS provides. Not ideal.....

@Ddog800, any chance you could share where to log in? I'm looking too. Documentation is poor. In Team Explorer, all I see is a message "Gitlab unlimited free repositories and collaborators..."

Thanks

**Comment by ewdwitkowski** [comment] 2019-12-03 10:55
> I have the same problem using VS2017Comunity and v1.0.176 as well. Never used it bevore have no existing connections. Not able to make it work.
> I created gitlab account by signing in with github account. Just in case it matters...

I had this issue too. You need to go to password settings on gitLab web site and set it. If you login with github account is your gitLab password not defined, and that's why you cannot connect.

**Comment by megant** [comment] 2020-01-24 11:11
Same here in 2020 (the problem occured first !!3!! years ago) 

Windows 10, VS2019, GitLab Extension v2.10.8.8132. Guys, seriously? :)
